/**
 * Regenerates lib/data/resume-text.ts from public/resume/Duane_Cabahug_Resume.pdf.
 * Run locally after updating the PDF: pnpm extract-resume
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { PDFParse } from "pdf-parse";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const pdfPath = path.join(root, "public/resume/Duane_Cabahug_Resume.pdf");
const outPath = path.join(root, "lib/data/resume-text.ts");

const data = fs.readFileSync(pdfPath);
const pdf = new PDFParse({ data });
const result = await pdf.getText();
await pdf.destroy();

let text = result.text.trim();
text = text.replace(/\n--\s*1 of 1\s*--\s*$/i, "").trim();
text = text.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/g, " ");
text = text.replace(/ +/g, " ");

const header = `// Auto-generated by scripts/extract-resume.mjs — run pnpm extract-resume after updating public/resume/Duane_Cabahug_Resume.pdf

export const resumeText = `;
const footer = " as const;\n";

fs.writeFileSync(outPath, `${header}${JSON.stringify(text)}${footer}`, "utf8");
console.log(`Wrote ${outPath} (${text.length} chars)`);
